name: kuebiko_client
version: 0.1.4
homepage: https://kuebiko.app
description: The API Client library for the ebook library software Kuebiko
environment:
  sdk: ^3.0.0
dependencies: 
  http: ^1.3.0
  image: ^4.5.3
  version: ^3.0.2
dev_dependencies: 
  test: ^1.25.15
  shelf: ^1.4.2
  shelf_router: ^1.1.4
